repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src/|tests/|scripts/|cloud-functions/).*\.py$
      - id: ruff-format
        files: ^(src/|tests/|scripts/|cloud-functions/).*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [
          types-requests,
          pydantic,
          pydantic-settings,
          structlog,
          flask,
          python-dotenv,
        ]
        args: [
          --ignore-missing-imports,
          --disallow-untyped-defs,
          --warn-return-any,
          --disable-error-code=misc,
          --disable-error-code=call-arg,
          --disable-error-code=no-any-return
        ]
        files: ^(src/whatsupdoc/|scripts/).*\.py$
        # Only run on main source code, not tests (due to missing stubs)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.(py|md|yaml|yml|json|toml)$
      - id: end-of-file-fixer
        files: \.(py|md|yaml|yml|json|toml)$
      - id: check-yaml
      - id: check-added-large-files
