[project]
name = "whatsupdoc"
version = "0.1.0"
description = "A Slack RAG chatbot using Vertex AI Search"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.0",
    "google-auth>=2.23.0", 
    "google-cloud-discoveryengine>=0.11.0",
    "slack-sdk>=3.23.0",
    "slack-bolt>=1.18.0",
    "flask>=2.3.0",
    "aiohttp>=3.8.0",
    "asyncio-throttle>=1.0.2",
    "structlog>=23.1.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "requests-mock>=1.11.0",
]
